services:
  emacs:
    image: emacs-devcontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/source:rw,Z
    command: /bin/sh -c "emacs --fg-daemon"
volumes:
  .:
