name: "Emacs Containerized Devcontainers"
root-directory: "/home/vscode/workspaces"
deps:
  - src: git@github.com:cuttlefisch/declarative-project-mode.git
  - src: git@github.com:cuttlefisch/prototype-emacs-devcontainer.git
local-files:
  - src: /workspaces/source/README.org
    dest: README.org
  - src: /workspaces/source/PROJECT.yaml
required-resources:
  - README.org
